
spring:
  datasource:
    name: mysql  #数据库名
    url: jdbc:mysql://localhost:3306/mysql #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

server:
  port: 8080