server:
  port: 8081

#普通写法
name: maodd

#对象写法
student:
  name: maodd
  age: 18

#行内写法
student1: { name: maodd,age: 18 }

#数组写法
pets:
  - cat
  - dog

#数组行内写法
pet1: [ cat,dog ]

person:
  name: maodd
  age: 18
  happy: true
  birth: 1993/01/10
  maps: { k1: v1,k2: v2 }
  list:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 1
  email:
